### ISSUE TITLE
world whitelist/blacklist issue

### ISSUE THREAD

**Issue by MrAmHamoham** [rockquiet/JoinProtection#6]
i tested world whitelist/blacklist feature but it doesn't work ,it only works when i set it on disabled.

**Comment by rockquiet** [comment]
Hi, can you give a some more information about your server (version, etc.) and the config section of the plugin?

Please try if this solves your problem:

- World names in the `world-list` are case sensitive (i.e. use the same name as the world folder)
- Verify that your config is valid on a site like: https://www.yamllint.com (uncheck "Reformat" to see any errors)

**Comment by MrAmHamoham** [comment]
It fixed, i think it's beacuse of cancelation section that it wasn't work
